services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    expose:
      - "80"
      - "443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./sites:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - application_network

volumes:
  caddy_data:
  caddy_config:

networks:
  application_network:
    external: true
